name: vp
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3
  - numpy
  - caffe
  - boost
  - pillow
  - opencv
  - requests
  - autopep8
  - pip
  - pip:
    - protobuf
    - opencv-contrib-python-headless
