# Generated by Django 3.1.6 on 2021-03-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='is_for_disabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoprocessortype',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingsite',
            name='cameras_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='parkingsite',
            name='lots_number',
            field=models.IntegerField(blank=True),
        ),
    ]
