# Generated by Django 3.1.6 on 2021-03-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210301_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoprocessortype',
            name='is_active',
        ),
        migrations.AddField(
            model_name='videoprocessor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='parking_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='api.parkingsite'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='video_processor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='api.videoprocessor'),
            preserve_default=False,
        ),
    ]
