# Generated by Django 3.1.6 on 2021-03-13 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parkinglot_video_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='position_on_board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), default=[1], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='shape_on_board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), default=[1], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), size=None),
        ),
    ]
