# Generated by Django 3.1.6 on 2021-03-23 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210313_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsite',
            name='description',
            field=models.CharField(default='sf;kjfdj', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingsite',
            name='latitude',
            field=models.FloatField(default=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingsite',
            name='longitude',
            field=models.FloatField(default=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingsite',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='position_on_board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='shape_on_board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
