# Generated by Django 3.1.6 on 2021-03-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210323_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsite',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
