# Generated by Django 3.1.6 on 2021-04-24 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210326_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=18)),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('is_on_parking', models.BooleanField(blank=True, default=False)),
                ('total_paid_time', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Acab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Minimal price error')])),
                ('free_threshold', models.IntegerField()),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.citizen')),
            ],
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='acab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.acab'),
        ),
    ]
