# Generated by Django 3.1.6 on 2021-05-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_acabs_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingsite',
            name='cameras_number',
        ),
        migrations.RemoveField(
            model_name='parkingsite',
            name='lots_number',
        ),
        migrations.AlterField(
            model_name='acab',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acabs', to='api.citizen'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='acab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='api.acab'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoprocessor',
            name='parking_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processors', to='api.parkingsite'),
        ),
    ]
