name: Core pipeline

on:
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: core

jobs:
  validate_code:
    name: Validate code
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: workflow_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r core/requirements.txt; fi
      - name: Run linter
        run: |
          flake8 --show-source .
      - name: Run tests
        env:
          DB_HOST: postgres
          DB_NAME: workflow_db
          DB_USER: user
          DB_PASSWORD: password
        run: |
          ./manage.py test
  run_code:
    name: Build container and run
    runs-on: ubuntu-latest
    needs: [ validate_code ]

    steps:
      - name: Build docker image
        uses: docker/build-push-action@v2.3.0
        with:
          file: Dockerfile
          tags: workflow_container:latest
          push: false